PREFIX  univ-bench: <http://swat.cse.lehigh.edu/onto/univ-bench.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?University_0
WHERE
  { ?University_0
              a                     univ-bench:University ;
              univ-bench:mastersDegreeFrom  ?ResearchAssistant_0
    MINUS
      { ?ResearchAssistant_0
                  a                     univ-bench:ResearchAssistant
        FILTER EXISTS { ?Organization_0
                                  univ-bench:memberOf  ?ResearchAssistant_0
                        { ObjectDescription:Manual_instance0
                                    univ-bench:orgPublication  ?Organization_0
                        }
                      }
      }
  }
