PREFIX  univ-bench: <http://swat.cse.lehigh.edu/onto/univ-bench.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?University_0
WHERE
  { ?University_0
              a                     univ-bench:University .
    ?GraduateStudent_0
              univ-bench:degreeFrom  ?University_0
    {   { ?GraduateStudent_0
                    a                     univ-bench:GraduateStudent
        }
      UNION
        { ?Course_0  univ-bench:takesCourse  ?GraduateStudent_0 }
    }
  }
