PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?CommunicationsSystem_0
WHERE
  { ?CommunicationsSystem_0
              a                     RFDevice:CommunicationsSystem
    { ?Var0  RFDevice:supportsTransmitting  ?CommunicationsSystem_0
      { ?Var0  a                     RFDevice:FixedBandwidthSensing
        { ?Var0  a                     RFDevice:BarrageJamming }
      }
    }
  }
