PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>

SELECT DISTINCT  ?USRPB200mini_i_0
WHERE
  { ?USRPB200mini_i_0
              a                     SDR:USRPB200mini-i
    MINUS
      { ?Var0  RFDevice:supportsSpectrumSensing  ?USRPB200mini_i_0
        { ?RadarFrequencyBand_0
                    RFDevice:hasBandwidthRange  ?Var0
          { ?RadarFrequencyBand_0
                      a                     RFDevice:RadarFrequencyBand
            OPTIONAL
              { ?Frequency_0  RFDevice:hasMax  ?RadarFrequencyBand_0
                { ?Frequency_0  a                 RFDevice:Frequency }
              }
          }
        }
      }
  }
