PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>

SELECT DISTINCT  ?USRPN3xx_0
WHERE
  { ?USRPN3xx_0  a                  SDR:USRPN3xx
    { ?USRPN3xx_0  RFDevice:supportsSpectrumSensing  ?Var0
      { ?Var0  a                     RFDevice:AdjustableBandwidthSensing
        { ?Attribute_0  RFDevice:hasPulseWidth  ?Var0 }
      }
    }
  }
