PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB200_210_0
WHERE
  { ?USRPB200_210_0
              a                     SDR:USRPB200-210
    { ?USRPB200_210_0
                RFDevice:supportsTransmitting  ?Var0
      {   { ?Var0  a                     RFDevice:CoverJamming }
        UNION
          { ?Quantity_0  Nuvio:hasProcessQuantity  ?Var0 }
      }
    }
  }
