PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?PulseDopplerRadar_0
WHERE
  { ?PulseDopplerRadar_0
              a                     RFDevice:PulseDopplerRadar
    { ?MobilePlatform_0
                RFDevice:isDeployedOn  ?PulseDopplerRadar_0
      { ?MobilePlatform_0
                  a                     RFDevice:MobilePlatform
        { ObjectDescription:Moving_instance51
                    RFDevice:supportsJamming  ?MobilePlatform_0
        }
      }
    }
  }
