PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?PulseDopplerRadar_0
WHERE
  { ?PulseDopplerRadar_0
              a                     RFDevice:PulseDopplerRadar
    { ?Object_0  RFDevice:isProducerOf  ?PulseDopplerRadar_0
      { ?Object_0  a                    Nuvio:Object .
        ObjectDescription:AntennaPolarization_instance20
                  Nuvio:hasObjectQuality  ?Object_0
      }
    }
  }
