PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?PulseRadar_0
WHERE
  { ?PulseRadar_0
              a                     RFDevice:PulseRadar
    { ?PulseRadarModulation_0
                RFDevice:hasCapability  ?PulseRadar_0
      { ?PulseRadarModulation_0
                  a                     RFDevice:PulseRadarModulation
        { ?PulseRadarModulation_0
                    RFDevice:hasTransmitPowerRange  ?Attribute_0
          { ?Attribute_0  a                 Nuvio:Attribute }
        }
      }
    }
  }
