PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?MonostaticRadar_0
WHERE
  { ?MonostaticRadar_0
              a                     RFDevice:MonostaticRadar
    MINUS
      { ?SuperheterodyneReceiver_0
                  Nuvio:partOf  ?MonostaticRadar_0
        { ?SuperheterodyneReceiver_0
                    a                     RFDevice:SuperheterodyneReceiver
        }
      }
  }
