PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>
PREFIX  gml:  <http://www.opengis.net/ont/gml#>

SELECT DISTINCT  ?SurveillanceRadar_0
WHERE
  { ?SurveillanceRadar_0
              a                     RFDevice:SurveillanceRadar
    { ?Entity_0  RFDevice:hasHeight  ?SurveillanceRadar_0
      { ?Entity_0  a                    Nuvio:Entity
        { ?Entity_0  a                    gml:Arc
          { ?Entity_0  a                    Nuvio:InformationRepresentation .
            ?InformationContent_0
                      Nuvio:representedBy   ?Entity_0
            { ?InformationContent_0
                        a                     Nuvio:InformationContent
            }
          }
        }
      }
    }
  }
