PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?Full_DuplexCommunicationsSystem_0
WHERE
  { ?Full_DuplexCommunicationsSystem_0
              a                     RFDevice:Full-DuplexCommunicationsSystem
    { ?Transmitting_0
                RFDevice:supportsJamming  ?Full_DuplexCommunicationsSystem_0
      { ?Power_0  RFDevice:hasMaxOutputPower  ?Transmitting_0
        { ?Power_0  a                     RFDevice:Power }
      }
    }
  }
