PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?RadarSystem_0
WHERE
  { ?RadarSystem_0
              a                     RFDevice:RadarSystem
    { ?Entity_0  Nuvio:compositeOf  ?RadarSystem_0
      {   { ?UnitOfMeasure_0
                      Nuvio:expresses  ?Entity_0
          }
        UNION
          { ?Entity_0  a                    RFDevice:AngleUnit }
      }
    }
  }
