PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>

SELECT DISTINCT  ?BistaticRadar_0
WHERE
  {   { ?BistaticRadar_0
                  a                     RFDevice:BistaticRadar
      }
    UNION
      { ?Quantity_0  RFDevice:hasWeight  ?BistaticRadar_0 }
  }
