PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPB210_0
WHERE
  { ?USRPB210_0  a                  SDR:USRPB210
    { ?XilinxFPGA_0
                Nuvio:partOf  ?USRPB210_0
      { ?XilinxFPGA_0
                  a                     SDR:XilinxFPGA
      }
    }
  }
