PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?SearchRadar_0
WHERE
  { ?SearchRadar_0
              a                     RFDevice:SearchRadar
    { ObjectDescription:MannedPlatform_instance41
                RFDevice:isDeployedOn  ?SearchRadar_0
    }
  }
