PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?GNURadio_0
WHERE
  { ?GNURadio_0  a                  SDR:GNURadio
    { ?Entity_0  RFDevice:isProducerOf  ?GNURadio_0
      { ?Entity_0  a                    Nuvio:Entity
        { ?Entity_0  a                    RFDevice:Full-DuplexCommunicationsSystem
          { ?Entity_0  a                    Nuvio:InformationEntity .
            ?Var0     Nuvio:informationSource  ?Entity_0
          }
        }
      }
    }
  }
