PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPN2xx_0
WHERE
  { ?USRPN2xx_0  a                  SDR:USRPN2xx
    { ?Var0  Nuvio:partOf  ?USRPN2xx_0
      { ?Var1  RFDevice:hasResolution  ?Var0 }
    }
  }
