PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?PulseRadar_0
WHERE
  { ?PulseRadar_0
              a                     RFDevice:PulseRadar
    { ?InstantaneousFrequencyMeasurementReceiver_0
                Nuvio:partOf  ?PulseRadar_0
      { ?InstantaneousFrequencyMeasurementReceiver_0
                  a                     RFDevice:InstantaneousFrequencyMeasurementReceiver
      }
    }
  }
