PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>

SELECT DISTINCT  ?USRPX300_0
WHERE
  { ?USRPX300_0  a                  SDR:USRPX300
    NOT EXISTS
      { ?USRPX300_0  RFDevice:isProducerOf  ?Entity_0
        { ?Entity_0  a                    RFDevice:LongitudeValue }
      }
  }
