PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?USRPN3xx_0
WHERE
  {   { ?USRPN3xx_0  a                  SDR:USRPN3xx }
    UNION
      { ?Object_0  RFDevice:isProducerOf  ?USRPN3xx_0
        { ?Object_0  a                    Nuvio:Object }
      }
  }
