PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ElectronicSupportSystem_0
WHERE
  { ?ElectronicSupportSystem_0
              a                     RFDevice:ElectronicSupportSystem
    MINUS
      { ?Entity_0  RFDevice:hasProducer  ?ElectronicSupportSystem_0
        {   { ?Quantity_0  RFDevice:hasHeight  ?Entity_0 }
          UNION
            { ?Entity_0  a                    Nuvio:InformationEntity
              { ?Entity_0  a                    Nuvio:Value .
                ?ElectricChargeUnit_0
                          Nuvio:hasUnitOfMeasure  ?Entity_0
              }
            }
        }
      }
  }
