PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?GNURadio_0
WHERE
  { ?GNURadio_0  a                  SDR:GNURadio
    { ?Receiver_0  Nuvio:partOf  ?GNURadio_0
      { ?Receiver_0  a                  RFDevice:Receiver }
    }
  }
