PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ElectronicAttackSystem_0
WHERE
  { ?ElectronicAttackSystem_0
              a                     RFDevice:ElectronicAttackSystem
    { ?RadioComponent_0
                Nuvio:aggregateOf  ?ElectronicAttackSystem_0
    }
  }
