PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?SurveillanceRadar_0
WHERE
  { ?SurveillanceRadar_0
              a                     RFDevice:SurveillanceRadar
    { ?Transmitter_0
                Nuvio:aggregateOf  ?SurveillanceRadar_0
      { ?Transmitter_0
                  a                     RFDevice:Transmitter
        { ?Entity_0  RFDevice:isProducerOf  ?Transmitter_0
          { ?UnitOfMeasure_0
                      Nuvio:isExpressedBy  ?Entity_0
            { ?Entity_0  a                    Nuvio:InformationContent }
          }
        }
      }
    }
  }
