PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?TrackingRadar_0
WHERE
  { ?TrackingRadar_0
              a                     RFDevice:TrackingRadar
    { ?Entity_0  RFDevice:isDeployedOn  ?TrackingRadar_0
      { ?Entity_0  a                    RFDevice:LatitudeValue
        FILTER NOT EXISTS { ?NoiseFigure_0
                                      RFDevice:hasLevel  ?Entity_0
                          }
        { ?Entity_0  a                    Nuvio:InformationRepresentation }
      }
    }
  }
