PREFIX  SDR:  <http://ece.neu.edu/ontologies/SDR.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?USRPX3xx_0
WHERE
  { ?USRPX3xx_0  a                  SDR:USRPX3xx }
