PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  RFDevice: <http://ece.neu.edu/ontologies/RFDevice.owl#>
PREFIX  Nuvio: <http://cogradio.org/ont/Nuvio.owl#>

SELECT DISTINCT  ?ElectronicAttackSystem_0
WHERE
  { ?ElectronicAttackSystem_0
              a                     RFDevice:ElectronicAttackSystem
    { ?Entity_0  RFDevice:hasWeight  ?ElectronicAttackSystem_0
      { ?Entity_0  a                    Nuvio:Entity
        {   { ?Time_0  RFDevice:hasPulseRepetitionInterval  ?Entity_0
              { ?Time_0  a                     RFDevice:Time }
            }
          UNION
            { ?Entity_0  a                    Nuvio:Attribute
              { ?Entity_0  a                    Nuvio:UnitOfMeasure }
            }
        }
      }
    }
  }
