PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  IoT-ontology: <http://kotis.epizy.com/Ontologies/IoT/IoT-ontology.owl#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?Resource_0
WHERE
  { ?Resource_0  a                  IoT-ontology:Resource .
    :Service_instance1
              ssn:observedBy        ?Resource_0
  }
