PREFIX  IoT-ontology: <http://kotis.epizy.com/Ontologies/IoT/IoT-ontology.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?ElectricMechanicDevice_0
WHERE
  { ?ElectricMechanicDevice_0
              a                     IoT-ontology:ElectricMechanicDevice
  }
