PREFIX  DUL:  <http://www.loa-cnr.it/ontologies/DUL.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  IoT-ontology: <http://kotis.epizy.com/Ontologies/IoT/IoT-ontology.owl#>

SELECT DISTINCT  ?SmartPhone_0
WHERE
  { ?SmartPhone_0
              a                     IoT-ontology:SmartPhone
    { ?System_0  DUL:hasComponent  ?SmartPhone_0 }
  }
