PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  IoT-ontology: <http://kotis.epizy.com/Ontologies/IoT/IoT-ontology.owl#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?Resource_0
WHERE
  { ?Resource_0  a                  IoT-ontology:Resource .
    ?ObservationService_0
              IoT-ontology:usesResource  ?Resource_0
    FILTER EXISTS { ?SensorOutput_0
                              ssn:featureOfInterest  ?ObservationService_0
                    { ?SensorOutput_0
                                a                     ssn:SensorOutput
                    }
                  }
  }
