PREFIX  DUL:  <http://www.loa-cnr.it/ontologies/DUL.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  IoT-ontology: <http://kotis.epizy.com/Ontologies/IoT/IoT-ontology.owl#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?Resource_0
WHERE
  { ?Resource_0  a                  IoT-ontology:Resource .
    ?ObservationService_0
              ssn:observedBy        ?Resource_0
    { ?ObservationService_0
                a                     IoT-ontology:ObservationService
      MINUS
        { ?ObservationService_0
                    DUL:isSettingFor  ?Quality_0
          { ?Quality_0  a                   DUL:Quality }
        }
    }
  }
