PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  IoT-ontology: <http://kotis.epizy.com/Ontologies/IoT/IoT-ontology.owl#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?ElectricMechanicDevice_0
WHERE
  { ?ElectricMechanicDevice_0
              a                     IoT-ontology:ElectricMechanicDevice
    NOT EXISTS
      { ?ElectricMechanicDevice_0
                  ssn:onPlatform  ?Platform_0
        { ?Platform_0  a                  ssn:Platform }
      }
  }
