PREFIX  DUL:  <http://www.loa-cnr.it/ontologies/DUL.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  IoT-ontology: <http://kotis.epizy.com/Ontologies/IoT/IoT-ontology.owl#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?ElectronicDevice_0
WHERE
  { ?ElectronicDevice_0
              a                     IoT-ontology:ElectronicDevice
    OPTIONAL
      { ?Platform_0  DUL:hasLocation  ?ElectronicDevice_0
        { ?Processor_0  DUL:hasLocation  ?Platform_0
          { ?Server_0  ssn:deploymentProcessPart  ?Processor_0
            { ?Server_0  a                    IoT-ontology:Server
              { ?Property_0  ssn:hasOperatingProperty  ?Server_0
                { ?Property_0  a                  ssn:Property }
              }
            }
          }
        }
      }
  }
