PREFIX  DUL:  <http://www.loa-cnr.it/ontologies/DUL.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  IoT-ontology: <http://kotis.epizy.com/Ontologies/IoT/IoT-ontology.owl#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?Platform_0
WHERE
  { ?Platform_0  a                  ssn:Platform
    { ?Deployment_0
                DUL:hasParticipant  ?Platform_0
      { ?Deployment_0
                  a                     ssn:Deployment
        FILTER NOT EXISTS { ?ComputingDevice_0
                                      DUL:hasParticipant  ?Deployment_0
                            { ?ComputingDevice_0
                                        a                     IoT-ontology:ComputingDevice
                              { ?DeploymentRelatedProcess_0
                                          DUL:hasParticipant  ?ComputingDevice_0
                                { ?Deployment_1
                                            ssn:deploymentProcessPart  ?DeploymentRelatedProcess_0
                                }
                              }
                            }
                          }
      }
    }
  }
