PREFIX  DUL:  <http://www.loa-cnr.it/ontologies/DUL.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  IoT-ontology: <http://kotis.epizy.com/Ontologies/IoT/IoT-ontology.owl#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?ElectricMechanicDevice_0
WHERE
  { ?ElectricMechanicDevice_0
              a                     IoT-ontology:ElectricMechanicDevice
    { ?RFID_tag_0  DUL:hasPart  ?ElectricMechanicDevice_0
      { ?RFID_tag_0  a                  IoT-ontology:RFID_tag
        { ?Quality_0  ssn:hasProperty  ?RFID_tag_0
          { ?Quality_0  a                   DUL:Quality }
        }
      }
    }
  }
