PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  IoT-ontology: <http://kotis.epizy.com/Ontologies/IoT/IoT-ontology.owl#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?Processor_0
WHERE
  { ?Processor_0  a                 IoT-ontology:Processor
    { ?Device_0  ssn:deploymentProcessPart  ?Processor_0
      { ?Device_0  a                    ssn:Device
        FILTER EXISTS { ?Processor_1  ssn:hasSubSystem  ?Device_0 }
      }
    }
  }
