PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  IoT-ontology: <http://kotis.epizy.com/Ontologies/IoT/IoT-ontology.owl#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?IdentityDevice_0
WHERE
  { ?IdentityDevice_0
              a                     IoT-ontology:IdentityDevice
    { ?ElectronicDevice_0
                ssn:hasSubSystem  ?IdentityDevice_0
      { ?ElectronicDevice_0
                  a                     IoT-ontology:ElectronicDevice
      }
    }
  }
