PREFIX  DUL:  <http://www.loa-cnr.it/ontologies/DUL.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  IoT-ontology: <http://kotis.epizy.com/Ontologies/IoT/IoT-ontology.owl#>

SELECT DISTINCT  ?PhysicalObject_0
WHERE
  { ?PhysicalObject_0
              a                     DUL:PhysicalObject .
    ?ElectricMechanicDevice_0
              DUL:hasLocation       ?PhysicalObject_0
    { ?ElectricMechanicDevice_0
                a                     IoT-ontology:ElectricMechanicDevice
    }
  }
