PREFIX  IoT-ontology: <http://kotis.epizy.com/Ontologies/IoT/IoT-ontology.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?Resource_0
WHERE
  { ?Resource_0  a                  IoT-ontology:Resource .
    ObjectDescription:Service_instance0
              IoT-ontology:resourceUsedIn  ?Resource_0
  }
