PREFIX  DUL:  <http://www.loa-cnr.it/ontologies/DUL.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?System_0
WHERE
  { ?System_0  a                    ssn:System
    { ?DeploymentRelatedProcess_0
                ssn:deployedSystem  ?System_0
      { ?Deployment_0
                  ssn:deploymentProcessPart  ?DeploymentRelatedProcess_0
        { ?Deployment_0
                    a                     ssn:Deployment
          FILTER NOT EXISTS { ?ActuatingDevice_0
                                        ssn:deployedOnPlatform  ?Deployment_0
                              { ?Process_0  ssn:deployedOnPlatform  ?ActuatingDevice_0
                                { ?Process_0  a                   DUL:Process }
                              }
                            }
        }
      }
    }
  }
