PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  IoT-ontology: <http://kotis.epizy.com/Ontologies/IoT/IoT-ontology.owl#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?SmartPhone_0
WHERE
  { ?SmartPhone_0
              a                     IoT-ontology:SmartPhone
    { ?Deployment_0
                ssn:deployedOnPlatform  ?SmartPhone_0
    }
  }
