PREFIX  DUL:  <http://www.loa-cnr.it/ontologies/DUL.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  IoT-ontology: <http://kotis.epizy.com/Ontologies/IoT/IoT-ontology.owl#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?ElectricMechanicDevice_0
WHERE
  { ?ElectricMechanicDevice_0
              a                     IoT-ontology:ElectricMechanicDevice
    { ?ElectricMechanicDevice_0
                ssn:attachedSystem  ?PhysicalObject_0
      { ?PhysicalObject_0
                  a                     DUL:PhysicalObject .
        ?SmartPhone_0
                  DUL:isLocationOf      ?PhysicalObject_0
      }
    }
  }
