PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  IoT-ontology: <http://kotis.epizy.com/Ontologies/IoT/IoT-ontology.owl#>

SELECT DISTINCT  ?ProcessingPower_0
WHERE
  { ?ProcessingPower_0
              a                     IoT-ontology:ProcessingPower
  }
