PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  IoT-ontology: <http://kotis.epizy.com/Ontologies/IoT/IoT-ontology.owl#>

SELECT DISTINCT  ?Processor_0
WHERE
  { ?Processor_0  a                 IoT-ontology:Processor }
