PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  IoT-ontology: <http://kotis.epizy.com/Ontologies/IoT/IoT-ontology.owl#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?ElectronicDevice_0
WHERE
  { ?ElectronicDevice_0
              a                     IoT-ontology:ElectronicDevice
    OPTIONAL
      { ?OperatingRange_0
                  ssn:hasMeasurementCapability  ?ElectronicDevice_0
      }
  }
