PREFIX  DUL:  <http://www.loa-cnr.it/ontologies/DUL.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  IoT-ontology: <http://kotis.epizy.com/Ontologies/IoT/IoT-ontology.owl#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?IdentityDevice_0
WHERE
  { ?IdentityDevice_0
              a                     IoT-ontology:IdentityDevice
    { ?ComputingDevice_0
                DUL:hasPart  ?IdentityDevice_0
      { ?ComputingDevice_0
                  a                     IoT-ontology:ComputingDevice
        { ObjectDescription:Platform_instance50
                    ssn:onPlatform  ?ComputingDevice_0
        }
      }
    }
  }
