PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  IoT-ontology: <http://kotis.epizy.com/Ontologies/IoT/IoT-ontology.owl#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?PersonalComputer_0
WHERE
  { ?PersonalComputer_0
              a                     IoT-ontology:PersonalComputer
    OPTIONAL
      { ?DeploymentRelatedProcess_0
                  ssn:inDeployment  ?PersonalComputer_0
      }
  }
