PREFIX  DUL:  <http://www.loa-cnr.it/ontologies/DUL.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?Platform_0
WHERE
  { ?Platform_0  a                  ssn:Platform
    { ?Process_0  ssn:hasDeployment  ?Platform_0
      { ?Process_0  a                   DUL:Process }
    }
  }
