PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  IoT-ontology: <http://kotis.epizy.com/Ontologies/IoT/IoT-ontology.owl#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?IdentityDevice_0
WHERE
  { ?IdentityDevice_0
              a                     IoT-ontology:IdentityDevice
    { ?RFID_tag_0  ssn:deploymentProcessPart  ?IdentityDevice_0
      { ?RFID_tag_0  ssn:hasMeasurementProperty  ?Property_0
        { :FeatureOfInterest_instance0
                    ssn:isPropertyOf  ?Property_0
        }
      }
    }
  }
