PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  ContextAwareness_eDIANA: <http://www.owl-ontologies.com/ContextAwareness_eDIANA.owl#>

SELECT DISTINCT  ?Generator_0
WHERE
  { ?Generator_0  a                 ContextAwareness_eDIANA:Generator
    { ?Configuration_Read_iEi_Service_0
                ContextAwareness_eDIANA:provided_services  ?Generator_0
      { ?Configuration_Read_iEi_Service_0
                  a                     ContextAwareness_eDIANA:Configuration_Read_iEi_Service
      }
    }
  }
