PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  ContextAwareness_eDIANA: <http://www.owl-ontologies.com/ContextAwareness_eDIANA.owl#>

SELECT DISTINCT  ?Video_Camera_0
WHERE
  { ?Video_Camera_0
              a                     ContextAwareness_eDIANA:Video_Camera
    { ?Var0  ContextAwareness_eDIANA:provided_services  ?Video_Camera_0
      { ?Var0  a                     ContextAwareness_eDIANA:UserData_Read_iEi_Service
        { ?Var0  a                     ContextAwareness_eDIANA:Internal_Service
          NOT EXISTS
            { ?Var0  a                     ContextAwareness_eDIANA:Reset_Command_Write_iEi_Service }
        }
      }
    }
  }
