PREFIX  ContextAwareness_eDIANA: <http://www.owl-ontologies.com/ContextAwareness_eDIANA.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?Airflow_Sensor_0
WHERE
  { ?Airflow_Sensor_0
              a                     ContextAwareness_eDIANA:Airflow_Sensor
  }
