PREFIX  ContextAwareness_eDIANA: <http://www.owl-ontologies.com/ContextAwareness_eDIANA.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?Sound_Sensor_0
WHERE
  { ?Sound_Sensor_0
              a                     ContextAwareness_eDIANA:Sound_Sensor
    { ContextAwareness_eDIANA:Noise_Information
                ContextAwareness_eDIANA:related_comfort_properties  ?Sound_Sensor_0
    }
  }
