PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ContextAwareness_eDIANA: <http://www.owl-ontologies.com/ContextAwareness_eDIANA.owl#>

SELECT DISTINCT  ?User_Interface_0
WHERE
  { ?User_Interface_0
              a                     ContextAwareness_eDIANA:User_Interface ;
              ContextAwareness_eDIANA:is_graphical  ?DataValue0
    FILTER ( ?DataValue0 <= true )
    ?Comfort_Variable_Information_0
              ContextAwareness_eDIANA:direction  ?User_Interface_0
    OPTIONAL
      { ?Var0  ContextAwareness_eDIANA:provided_services  ?User_Interface_0
        { ?Var0  a                     ContextAwareness_eDIANA:Command_Write_iEi_Service
          NOT EXISTS
            { ?Var0  a                     ContextAwareness_eDIANA:Internal_Service }
        }
        OPTIONAL
          { ?Comfort_Variable_Information_0
                      a                     ContextAwareness_eDIANA:Comfort_Variable_Information
          }
      }
  }
