PREFIX  ContextAwareness_eDIANA: <http://www.owl-ontologies.com/ContextAwareness_eDIANA.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?Boolean_Actuator_0
WHERE
  { ?Boolean_Actuator_0
              a                     ContextAwareness_eDIANA:Boolean_Actuator
  }
