PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ContextAwareness_eDIANA: <http://www.owl-ontologies.com/ContextAwareness_eDIANA.owl#>

SELECT DISTINCT  ?Value_Actuator_0
WHERE
  { ?Value_Actuator_0
              a                     ContextAwareness_eDIANA:Value_Actuator ;
              ContextAwareness_eDIANA:is_digital  ?DataValue0
    FILTER ( ?DataValue0 < false )
  }
