PREFIX  ContextAwareness_eDIANA: <http://www.owl-ontologies.com/ContextAwareness_eDIANA.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?Storage_0
WHERE
  { ?Storage_0  a                   ContextAwareness_eDIANA:Storage
    MINUS
      { ?Storage_0  ContextAwareness_eDIANA:provided_services  ?Profile_Read_iEi_Service_0
        { ?Profile_Read_iEi_Service_0
                    a                     ContextAwareness_eDIANA:Profile_Read_iEi_Service
        }
      }
  }
