PREFIX  ContextAwareness_eDIANA: <http://www.owl-ontologies.com/ContextAwareness_eDIANA.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?Value_Actuator_0
WHERE
  { ?Value_Actuator_0
              a                     ContextAwareness_eDIANA:Value_Actuator
    { ?Var0  ContextAwareness_eDIANA:provided_services  ?Value_Actuator_0
      { ?Var0  a                     ContextAwareness_eDIANA:Status_Read_iEi_Service }
    }
  }
