PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  ContextAwareness_eDIANA: <http://www.owl-ontologies.com/ContextAwareness_eDIANA.owl#>

SELECT DISTINCT  ?Power_Sensor_0
WHERE
  { ?Power_Sensor_0
              a                     ContextAwareness_eDIANA:Power_Sensor
    { ?Power_Sensor_0
                ContextAwareness_eDIANA:provided_services  ?Var0
      { ?Var0  a                     ContextAwareness_eDIANA:Status_Read_iEi_Service
        { ?Var0  a                     ContextAwareness_eDIANA:Service }
      }
    }
  }
