PREFIX  ContextAwareness_eDIANA: <http://www.owl-ontologies.com/ContextAwareness_eDIANA.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?Smoke_Sensor_0
WHERE
  { ?Smoke_Sensor_0
              a                     ContextAwareness_eDIANA:Smoke_Sensor
    { ?Var0  ContextAwareness_eDIANA:provided_services  ?Smoke_Sensor_0
      { ?Var0  a                     ContextAwareness_eDIANA:Service
        { ?Var0  a                     ContextAwareness_eDIANA:Internal_Service }
        { ?Var0  a                     ContextAwareness_eDIANA:UserData_Read_iEi_Service }
      }
    }
  }
