PREFIX  ContextAwareness_eDIANA: <http://www.owl-ontologies.com/ContextAwareness_eDIANA.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?Temperature_Sensor_0
WHERE
  { ?Temperature_Sensor_0
              a                     ContextAwareness_eDIANA:Temperature_Sensor
    { ?Var0  ContextAwareness_eDIANA:related_comfort_properties  ?Temperature_Sensor_0 }
  }
