PREFIX  ContextAwareness_eDIANA: <http://www.owl-ontologies.com/ContextAwareness_eDIANA.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?Trigger_Actuator_0
WHERE
  { ?Trigger_Actuator_0
              a                     ContextAwareness_eDIANA:Trigger_Actuator
    { ?Var0  ContextAwareness_eDIANA:provided_services  ?Trigger_Actuator_0
      { ?Var0  a                     ContextAwareness_eDIANA:Configuration_Read_iEi_Service
        FILTER NOT EXISTS { ?Var0  a                     ContextAwareness_eDIANA:Reset_Command_Write_iEi_Service }
      }
    }
  }
