PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  ContextAwareness_eDIANA: <http://www.owl-ontologies.com/ContextAwareness_eDIANA.owl#>

SELECT DISTINCT  ?Switch_Actuator_0
WHERE
  { ?Switch_Actuator_0
              a                     ContextAwareness_eDIANA:Switch_Actuator
  }
