PREFIX  ContextAwareness_eDIANA: <http://www.owl-ontologies.com/ContextAwareness_eDIANA.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?Boolean_Actuator_0
WHERE
  { ?Boolean_Actuator_0
              a                     ContextAwareness_eDIANA:Boolean_Actuator
    { ?Var0  ContextAwareness_eDIANA:provided_services  ?Boolean_Actuator_0
      { ?Var0  a                     ContextAwareness_eDIANA:LogData_Write_iEi_Service
        { ?Var0  a                     ContextAwareness_eDIANA:Configuration_Read_iEi_Service }
      }
    }
  }
