PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ContextAwareness_eDIANA: <http://www.owl-ontologies.com/ContextAwareness_eDIANA.owl#>

SELECT DISTINCT  ?Physical_Sensor_0
WHERE
  { ?Physical_Sensor_0
              a                     ContextAwareness_eDIANA:Physical_Sensor ;
              ContextAwareness_eDIANA:min_value  ?DataValue0
    FILTER ( ?DataValue0 >= -556821870 )
  }
