PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  ContextAwareness_eDIANA: <http://www.owl-ontologies.com/ContextAwareness_eDIANA.owl#>

SELECT DISTINCT  ?Complex_Device_0
WHERE
  { ?Complex_Device_0
              a                     ContextAwareness_eDIANA:Complex_Device
  }
