PREFIX  ContextAwareness_eDIANA: <http://www.owl-ontologies.com/ContextAwareness_eDIANA.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?Generator_0
WHERE
  { ?Generator_0  a                 ContextAwareness_eDIANA:Generator
    { ?Profile_Read_iEi_Service_0
                ContextAwareness_eDIANA:provided_services  ?Generator_0
      { ?Profile_Read_iEi_Service_0
                  a                     ContextAwareness_eDIANA:Profile_Read_iEi_Service
      }
    }
  }
