PREFIX  ContextAwareness_eDIANA: <http://www.owl-ontologies.com/ContextAwareness_eDIANA.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?Video_Camera_0
WHERE
  { ?Video_Camera_0
              a                     ContextAwareness_eDIANA:Video_Camera
  }
