PREFIX  ContextAwareness_eDIANA: <http://www.owl-ontologies.com/ContextAwareness_eDIANA.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?Device_0
WHERE
  { ?Device_0  a                    ContextAwareness_eDIANA:Device ;
              ContextAwareness_eDIANA:provided_services  ?Value_Command_Write_iEi_Service_0
  }
