PREFIX  saref: <https://w3id.org/saref#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?SmokeSensor_0
WHERE
  { ?SmokeSensor_0
              a                     saref:SmokeSensor
    { ?Energy_0  saref:measuresProperty  ?SmokeSensor_0
      { ?Energy_0  a                    saref:Energy
        FILTER NOT EXISTS { ?Measurement_0
                                      saref:relatesToMeasurement  ?Energy_0
                            { ?Measurement_0
                                        a                     saref:Measurement
                            }
                          }
      }
    }
  }
