PREFIX  saref: <https://w3id.org/saref#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?DoorSwitch_0
WHERE
  { ?DoorSwitch_0
              a                     saref:DoorSwitch
    { ?Light_0  saref:measuresProperty  ?DoorSwitch_0
      { ?Light_0  a                     saref:Light
        FILTER NOT EXISTS { ?Light_0  saref:relatesToMeasurement  ObjectDescription:Measurement_instance810 }
      }
    }
  }
