PREFIX  saref: <https://w3id.org/saref#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?Appliance_0
WHERE
  { ?Appliance_0  a                 saref:Appliance
    { ?Energy_0  saref:measuresProperty  ?Appliance_0
      { ?Energy_0  a                    saref:Energy }
    }
  }
