PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  saref: <https://w3id.org/saref#>

SELECT DISTINCT  ?FunctionRelated_0
WHERE
  { ?FunctionRelated_0
              a                     saref:FunctionRelated
    { ?Profile_0  saref:hasProfile  ?FunctionRelated_0
      { ?Profile_0  a                   saref:Profile }
    }
  }
