PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  saref: <https://w3id.org/saref#>

SELECT DISTINCT  ?LightSwitch_0
WHERE
  { ?LightSwitch_0
              a                     saref:LightSwitch
  }
