PREFIX  saref: <https://w3id.org/saref#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?MicroRenewable_0
WHERE
  { ?MicroRenewable_0
              a                     saref:MicroRenewable
    { ?MultiLevelState_0
                saref:hasState  ?MicroRenewable_0
      { ?MultiLevelState_0
                  a                     saref:MultiLevelState
      }
    }
  }
