PREFIX  saref: <https://w3id.org/saref#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?LightSwitch_0
WHERE
  { ?LightSwitch_0
              a                     saref:LightSwitch
    { ?Light_0  saref:measuresProperty  ?LightSwitch_0
      { ?Measurement_0
                  saref:relatesToMeasurement  ?Light_0
        { ?Measurement_0
                    a                     saref:Measurement
        }
      }
    }
  }
