PREFIX  saref: <https://w3id.org/saref#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?Appliance_0
WHERE
  { ?Appliance_0  a                 saref:Appliance
    { ?Var0  saref:hasTypicalConsumption  ?Appliance_0
      { ?Var0  a                     saref:Property
        { ObjectDescription:Appliance_instance32
                    saref:isControlledByDevice  ?Var0
        }
      }
    }
  }
