PREFIX  saref: <https://w3id.org/saref#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?Appliance_0
WHERE
  { ?Appliance_0  a                 saref:Appliance
    { ?Humidity_0  saref:controlsProperty  ?Appliance_0
      { ?Humidity_0  a                  saref:Humidity
        { ?Sensor_0  saref:isMeasuredByDevice  ?Humidity_0
          { ?Sensor_0  a                    saref:Sensor }
        }
      }
    }
  }
