PREFIX  saref: <https://w3id.org/saref#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?Appliance_0
WHERE
  { ?Appliance_0  a                 saref:Appliance
    { ?Appliance_0  saref:hasManufacturer  ?DataValue0 }
  }
