PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  saref: <https://w3id.org/saref#>

SELECT DISTINCT  ?TemperatureSensor_0
WHERE
  { ?TemperatureSensor_0
              a                     saref:TemperatureSensor
    EXISTS
      { ?Sensor_0  saref:consistsOf  ?TemperatureSensor_0
        { ?Sensor_0  a                    saref:Sensor }
      }
  }
