PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  saref: <https://w3id.org/saref#>

SELECT DISTINCT  ?WashingMachine_0
WHERE
  { ?WashingMachine_0
              a                     saref:WashingMachine
    { ?Measurement_0
                saref:makesMeasurement  ?WashingMachine_0
    }
  }
