PREFIX  saref: <https://w3id.org/saref#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?TemperatureSensor_0
WHERE
  { ?TemperatureSensor_0
              a                     saref:TemperatureSensor
    FILTER EXISTS { ?TemperatureSensor_0
                              saref:hasDescription  ?DataValue0
                  }
  }
