PREFIX  saref: <https://w3id.org/saref#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?EnergyRelated_0
WHERE
  { ?EnergyRelated_0
              a                     saref:EnergyRelated
    FILTER NOT EXISTS { ObjectDescription:Commodity_instance23
                                  saref:isUsedFor  ?EnergyRelated_0
                      }
  }
