PREFIX  saref: <https://w3id.org/saref#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?LightingDevice_0
WHERE
  { ?LightingDevice_0
              a                     saref:LightingDevice
    { ?LightingDevice_0
                saref:hasDescription  ?DataValue0
    }
  }
