PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  saref: <https://w3id.org/saref#>

SELECT DISTINCT  ?SmokeSensor_0
WHERE
  { ?SmokeSensor_0
              a                     saref:SmokeSensor
    { ?Time_0  saref:measuresProperty  ?SmokeSensor_0
      { ?Time_0  a                     saref:Time }
    }
  }
