PREFIX  saref: <https://w3id.org/saref#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?Switch_0
WHERE
  { ?Switch_0  a                    saref:Switch
    { ?LevelControlFunction_0
                saref:hasFunction  ?Switch_0
      { ?LevelControlFunction_0
                  saref:hasCommand  ?CloseCommand_0
        { ?CloseCommand_0
                    a                     saref:CloseCommand
          { ?OpenState_0  saref:actsUpon  ?CloseCommand_0
            { ?OpenState_0  a                 saref:OpenState }
          }
        }
      }
    }
  }
