PREFIX  saref: <https://w3id.org/saref#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?WashingMachine_0
WHERE
  { ?WashingMachine_0
              a                     saref:WashingMachine
    MINUS
      { ?WashingMachine_0
                  saref:controlsProperty  ObjectDescription:Instance1999
      }
  }
