PREFIX  saref: <https://w3id.org/saref#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?LightingDevice_0
WHERE
  { ?LightingDevice_0
              a                     saref:LightingDevice
    FILTER NOT EXISTS { ?Var0  saref:hasTypicalConsumption  ?LightingDevice_0
                        { ?Var0  a                     saref:Property
                          { ?DoorSwitch_0
                                      saref:isControlledByDevice  ?Var0
                            { ?DoorSwitch_0
                                        a                     saref:DoorSwitch
                            }
                          }
                        }
                      }
  }
