PREFIX  saref: <https://w3id.org/saref#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?SmokeSensor_0
WHERE
  { ?SmokeSensor_0
              a                     saref:SmokeSensor
  }
