PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  saref: <https://w3id.org/saref#>

SELECT DISTINCT  ?Actuator_0
WHERE
  { ?Actuator_0  a                  saref:Actuator
    { ?Actuator_0  saref:hasDescription  ?DataValue0 }
  }
