PREFIX  saref: <https://w3id.org/saref#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?WashingMachine_0
WHERE
  { ?WashingMachine_0
              a                     saref:WashingMachine
    { ?WashingMachine_0
                saref:hasDescription  ?DataValue0
    }
  }
