PREFIX  saref: <https://w3id.org/saref#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?Device_0
WHERE
  { ?Device_0  a                    saref:Device
    { ?StartStopFunction_0
                saref:hasFunction  ?Device_0
    }
  }
