PREFIX  saref: <https://w3id.org/saref#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?Storage_0
WHERE
  { ?Storage_0  a                   saref:Storage
    { ?Storage_0  saref:hasModel  ?DataValue0 }
  }
