PREFIX  saref: <https://w3id.org/saref#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?Network_0
WHERE
  { ?Network_0  a                   saref:Network
    { ?Measurement_0
                saref:makesMeasurement  ?Network_0
      { ?Motion_0  saref:relatesToProperty  ?Measurement_0
        { ?Motion_0  a                    saref:Motion }
      }
    }
  }
