PREFIX  saref: <https://w3id.org/saref#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?Network_0
WHERE
  { ?Network_0  a                   saref:Network
    { ?SmokeSensor_0
                saref:consistsOf  ?Network_0
      {   { ?SmokeSensor_0
                      a                     saref:SmokeSensor
          }
        UNION
          { ?SmokeSensor_0
                      saref:hasManufacturer  ?DataValue0
          }
      }
    }
  }
