PREFIX  saref: <https://w3id.org/saref#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?EnergyMeter_0
WHERE
  { ?EnergyMeter_0
              a                     saref:EnergyMeter
    { ?Water_0  saref:isUsedFor  ?EnergyMeter_0
      { ?Currency_0  saref:isMeasuredIn  ?Water_0 }
    }
  }
