PREFIX  saref: <https://w3id.org/saref#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?Storage_0
WHERE
  { ?Storage_0  a                   saref:Storage
    { ?Task_0  saref:isAccomplishedBy  ?Storage_0
      { ?Task_0  a                     saref:Task
        { ?EnergyRelated_0
                    saref:isAccomplishedBy  ?Task_0
          { ?EnergyRelated_0
                      a                     saref:EnergyRelated
          }
        }
      }
    }
  }
