PREFIX  saref: <https://w3id.org/saref#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?MicroRenewable_0
WHERE
  { ?MicroRenewable_0
              a                     saref:MicroRenewable
    OPTIONAL
      { ?Task_0  saref:isAccomplishedBy  ?MicroRenewable_0
        { ?Task_0  a                     saref:Task }
      }
  }
