PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  saref: <https://w3id.org/saref#>

SELECT DISTINCT  ?Actuator_0
WHERE
  { ?Actuator_0  a                  saref:Actuator
    { ?Actuator_0  saref:isOfferedBy  ?Service_0
      { ?Service_0  a                   saref:Service
        { ?EventFunction_0
                    saref:represents  ?Service_0
          { ?EventFunction_0
                      a                     saref:EventFunction
          }
        }
      }
    }
  }
