PREFIX  saref: <https://w3id.org/saref#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?MicroRenewable_0
WHERE
  { ?MicroRenewable_0
              a                     saref:MicroRenewable
    { ObjectDescription:EnergyRelated_instance128
                saref:consistsOf  ?MicroRenewable_0
    }
  }
