PREFIX  saref: <https://w3id.org/saref#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?Device_0
WHERE
  { ?Device_0  a                    saref:Device
    FILTER EXISTS { ?Var0  saref:hasTypicalConsumption  ?Device_0
                    { ?Var0  saref:relatesToMeasurement  ObjectDescription:Measurement_instance319 }
                  }
  }
