PREFIX  saref: <https://w3id.org/saref#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?Generator_0
WHERE
  { ?Generator_0  a                 saref:Generator
    { ?Task_0  saref:accomplishes  ?Generator_0
      { ?Task_0  a                     saref:Task }
    }
  }
