PREFIX  saref: <https://w3id.org/saref#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?Generator_0
WHERE
  { ?Generator_0  a                 saref:Generator
    { ?Generator_0  saref:hasTypicalConsumption  ?Var0
      { ?Var0  a                     saref:Property }
    }
  }
