PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  saref: <https://w3id.org/saref#>

SELECT DISTINCT  ?Meter_0
WHERE
  { ?Meter_0  a                     saref:Meter
    { ?MeteringFunction_0
                saref:hasFunction  ?Meter_0
      {   { ?MeteringFunction_0
                      a                     saref:MeteringFunction
          }
        UNION
          { ?Measurement_0
                      saref:hasMeterReading  ?MeteringFunction_0
            { :Energy_instance25
                        saref:relatesToProperty  ?Measurement_0
            }
          }
      }
    }
  }
