PREFIX  saref: <https://w3id.org/saref#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?BuildingRelated_0
WHERE
  { ?BuildingRelated_0
              a                     saref:BuildingRelated
  }
