PREFIX  saref: <https://w3id.org/saref#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?HVAC_0
WHERE
  { ?HVAC_0  a                     saref:HVAC
    { ObjectDescription:MultiLevelState_instance12
                saref:hasState  ?HVAC_0
    }
  }
