PREFIX  saref: <https://w3id.org/saref#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?Meter_0
WHERE
  { ?Meter_0  a                     saref:Meter
    { ?Var0  saref:hasTypicalConsumption  ?Meter_0 }
  }
