PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  saref: <https://w3id.org/saref#>

SELECT DISTINCT  ?Generator_0
WHERE
  { ?Generator_0  a                 saref:Generator
    { ?Commodity_0  saref:isUsedFor  ?Generator_0
      { ?Commodity_0  a                 saref:Commodity }
    }
  }
