PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  time: <http://www.w3.org/2006/time#>
PREFIX  saref: <https://w3id.org/saref#>

SELECT DISTINCT  ?Load_0
WHERE
  { ?Load_0  a                     saref:Load
    { ?Commodity_0  saref:isUsedFor  ?Load_0
      { ?Commodity_0  a                 saref:Commodity
        { ?Commodity_0  saref:isMeasuredIn  ?TemporalUnit_0
          { ?TemporalUnit_0
                      a                     time:TemporalUnit
          }
        }
      }
    }
  }
