PREFIX  saref: <https://w3id.org/saref#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?Multimedia_0
WHERE
  { ?Multimedia_0
              a                     saref:Multimedia
    { ?Multimedia_0
                saref:hasDescription  ?DataValue0
    }
  }
