PREFIX  saref: <https://w3id.org/saref#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?SmokeSensor_0
WHERE
  { ?SmokeSensor_0
              a                     saref:SmokeSensor
    { ?Load_0  saref:consistsOf  ?SmokeSensor_0
      { ?Load_0  a                     saref:Load
        { ObjectDescription:Service_instance282
                    saref:offers  ?Load_0
        }
      }
    }
  }
