PREFIX  saref: <https://w3id.org/saref#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?Network_0
WHERE
  { ?Network_0  a                   saref:Network
    { ObjectDescription:Instance1539
                saref:controlsProperty  ?Network_0
    }
  }
