PREFIX  saref: <https://w3id.org/saref#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?FunctionRelated_0
WHERE
  { ?FunctionRelated_0
              a                     saref:FunctionRelated
    { ?Price_0  saref:controlsProperty  ?FunctionRelated_0
      { ?Price_0  a                     saref:Price }
    }
  }
