PREFIX  saref: <https://w3id.org/saref#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?DoorSwitch_0
WHERE
  { ?DoorSwitch_0
              a                     saref:DoorSwitch
    { ?DoorSwitch_0
                saref:hasModel  ?DataValue0
    }
  }
