PREFIX  saref: <https://w3id.org/saref#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?Appliance_0
WHERE
  { ?Appliance_0  a                 saref:Appliance
    { ?Task_0  saref:accomplishes  ?Appliance_0
      { ?Task_0  a                     saref:Task
        { ?LightSwitch_0
                    saref:accomplishes  ?Task_0
          { ?LightSwitch_0
                      a                     saref:LightSwitch
            { ?Task_1  saref:isAccomplishedBy  ?LightSwitch_0 }
          }
        }
      }
    }
  }
