PREFIX  saref: <https://w3id.org/saref#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?Load_0
WHERE
  { ?Load_0  a                     saref:Load
    { ?Profile_0  saref:hasProfile  ?Load_0 }
  }
