PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?System_0
WHERE
  { ?System_0  a                    ssn:System
    MINUS
      { ?OperatingRange_0
                  ssn:hasMeasurementCapability  ?System_0
        { ?OperatingRange_0
                    a                     ssn:OperatingRange
        }
      }
  }
