PREFIX  DUL:  <http://www.loa-cnr.it/ontologies/DUL.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  WM30: <http://purl.oclc.org/NET/ssnx/meteo/WM30#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?Vaisala_WM30_0
WHERE
  { ?Vaisala_WM30_0
              a                     WM30:Vaisala_WM30
    OPTIONAL
      { ?Quality_0  ssn:observes  ?Vaisala_WM30_0
        { ?Quality_0  a                   DUL:Quality }
      }
  }
