PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?Device_0
WHERE
  { ?Device_0  a                    ssn:Device
    OPTIONAL
      { ?Vaisala_WM30_0
                  ssn:deploymentProcessPart  ?Device_0
        { ?PhysicalObject_0
                    ssn:deploymentProcessPart  ?Vaisala_WM30_0
        }
      }
  }
