PREFIX  DUL:  <http://www.loa-cnr.it/ontologies/DUL.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?System_0
WHERE
  { ?System_0  a                    ssn:System
    { ?DeploymentRelatedProcess_0
                DUL:hasParticipant  ?System_0
      { ?DeploymentRelatedProcess_0
                  a                     ssn:DeploymentRelatedProcess
        { ?Process_0  DUL:hasPart  ?DeploymentRelatedProcess_0
          { ?Process_0  a                   DUL:Process }
        }
      }
    }
  }
