PREFIX  DUL:  <http://www.loa-cnr.it/ontologies/DUL.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  WM30: <http://purl.oclc.org/NET/ssnx/meteo/WM30#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?WM30_WindDirection_0
WHERE
  { ?WM30_WindDirection_0
              a                     WM30:WM30_WindDirection
    FILTER EXISTS { ?SensorInput_0
                              ssn:detects  ?WM30_WindDirection_0
                    { ?Condition_0  ssn:isProxyFor  ?SensorInput_0
                      { ObjectDescription:WindFeature_instance10
                                  DUL:hasQuality  ?Condition_0
                      }
                    }
                  }
  }
