PREFIX  DUL:  <http://www.loa-cnr.it/ontologies/DUL.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?Device_0
WHERE
  { ?Device_0  a                    ssn:Device
    { ?Deployment_0
                ssn:deployedSystem  ?Device_0
      { ?Deployment_0
                  a                     ssn:Deployment
        { ?Deployment_0
                    ssn:hasSubSystem  ?Process_0
          { ?Process_0  a                   DUL:Process }
        }
      }
    }
  }
