PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?SensingDevice_0
WHERE
  { ?SensingDevice_0
              a                     ssn:SensingDevice
    { ?SensingDevice_0
                ssn:hasSubSystem  ?Vaisala_WM30_0
    }
  }
