PREFIX  DUL:  <http://www.loa-cnr.it/ontologies/DUL.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?Platform_0
WHERE
  { ?Platform_0  a                  ssn:Platform
    { ?Platform_0  DUL:isLocationOf  ?Vaisala_WM30_0
      { ?Vaisala_WM30_0
                  DUL:hasPart  ?PhysicalObject_0
        { ?PhysicalObject_0
                    a                     DUL:PhysicalObject
        }
      }
    }
  }
