PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?Device_0
WHERE
  { ?Device_0  a                    ssn:Device
    OPTIONAL
      { ?PhysicalObject_0
                  ssn:hasSubSystem  ?Device_0
      }
  }
