PREFIX  DUL:  <http://www.loa-cnr.it/ontologies/DUL.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?Device_0
WHERE
  { ?Device_0  a                    ssn:Device
    { ?Device_0  ssn:deploymentProcessPart  ?PhysicalObject_0
      { ?PhysicalObject_0
                  a                     DUL:PhysicalObject
      }
    }
  }
