PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?SensingDevice_0
WHERE
  { ?SensingDevice_0
              a                     ssn:SensingDevice
    MINUS
      { ?SensingDevice_0
                  ssn:isPropertyOf  ?OperatingRange_0
        { ?OperatingRange_0
                    a                     ssn:OperatingRange
          { ?Condition_0  ssn:inCondition  ?OperatingRange_0 }
        }
      }
  }
