PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?SensingDevice_0
WHERE
  { ?SensingDevice_0
              a                     ssn:SensingDevice
    { ?OverShootRatio_0
                ssn:observes  ?SensingDevice_0
      { ?WindFeature_0
                  ssn:hasOperatingProperty  ?OverShootRatio_0
      }
    }
  }
