PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  DUL:  <http://www.loa-cnr.it/ontologies/DUL.owl#>
PREFIX  WM30: <http://purl.oclc.org/NET/ssnx/meteo/WM30#>

SELECT DISTINCT  ?WM30_WindDirection_0
WHERE
  { ?WM30_WindDirection_0
              a                     WM30:WM30_WindDirection
    { ?WM30_CharacteristicTransferFunction_0
                DUL:isDescribedBy  ?WM30_WindDirection_0
      { ?WM30_CharacteristicTransferFunction_0
                  a                     WM30:WM30_CharacteristicTransferFunction
      }
    }
  }
