PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  WM30: <http://purl.oclc.org/NET/ssnx/meteo/WM30#>
PREFIX  qu:   <http://purl.oclc.org/NET/ssnx/qu/qu#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?WMS301_0
WHERE
  { ?WMS301_0  a                    WM30:WMS301
    { ?QuantityKind_0
                ssn:observes  ?WMS301_0
      { ?QuantityKind_0
                  qu:name  ?DataValue0
      }
    }
  }
