PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  DUL:  <http://www.loa-cnr.it/ontologies/DUL.owl#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?Device_0
WHERE
  { ?Device_0  a                    ssn:Device
    { ?Process_0  ssn:hasDeployment  ?Device_0
      { ?Process_0  a                   DUL:Process }
    }
  }
