PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?Sensor_0
WHERE
  { ?Sensor_0  a                    ssn:Sensor
    { ?Sensor_0  ssn:detects  ?Stimulus_0
      { ?Stimulus_0  a                  ssn:Stimulus }
    }
  }
