PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  WM30: <http://purl.oclc.org/NET/ssnx/meteo/WM30#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?WMS301_0
WHERE
  { ?WMS301_0  a                    WM30:WMS301
    { ObjectDescription:WM30_WindDirection_MeasurementCapability_WMS301_instance7
                ssn:hasMeasurementCapability  ?WMS301_0
    }
  }
