PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  DUL:  <http://www.loa-cnr.it/ontologies/DUL.owl#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?SensingDevice_0
WHERE
  {   { ?SensingDevice_0
                  a                     ssn:SensingDevice
      }
    UNION
      { ?Quality_0  ssn:hasOperatingRange  ?SensingDevice_0
        { ?Quality_0  a                   DUL:Quality }
      }
  }
