PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  WM30: <http://purl.oclc.org/NET/ssnx/meteo/WM30#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?WMS302_0
WHERE
  { ?WMS302_0  a                    WM30:WMS302
    { ?WindDirection_0
                ssn:observes  ?WMS302_0
    }
  }
