PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  WM30: <http://purl.oclc.org/NET/ssnx/meteo/WM30#>

SELECT DISTINCT  ?WM30_WindSpeed_0
WHERE
  { ?WM30_WindSpeed_0
              a                     WM30:WM30_WindSpeed
  }
