PREFIX  DUL:  <http://www.loa-cnr.it/ontologies/DUL.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?System_0
WHERE
  { ?System_0  a                    ssn:System
    { ObjectDescription:SensingDevice_instance218
                DUL:hasPart  ?System_0
    }
  }
