PREFIX  DUL:  <http://www.loa-cnr.it/ontologies/DUL.owl#>
PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>

SELECT DISTINCT  ?PhysicalObject_0
WHERE
  { ?PhysicalObject_0
              a                     DUL:PhysicalObject
  }
