PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  DUL:  <http://www.loa-cnr.it/ontologies/DUL.owl#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?Platform_0
WHERE
  { ?Platform_0  a                  ssn:Platform
    NOT EXISTS
      { ?PhysicalObject_0
                  ssn:onPlatform  ?Platform_0
        { ?PhysicalObject_0
                    a                     DUL:PhysicalObject
        }
      }
  }
