PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  DUL:  <http://www.loa-cnr.it/ontologies/DUL.owl#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?System_0
WHERE
  { ?System_0  a                    ssn:System
    MINUS
      { ?SurvivalRange_0
                  ssn:hasSurvivalRange  ?System_0
        { :WindFeature_instance85
                    DUL:isQualityOf  ?SurvivalRange_0
        }
      }
  }
