PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  DUL:  <http://www.loa-cnr.it/ontologies/DUL.owl#>
PREFIX  WM30: <http://purl.oclc.org/NET/ssnx/meteo/WM30#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?WM30_WindDirection_0
WHERE
  { ?WM30_WindDirection_0
              a                     WM30:WM30_WindDirection
    { ?Quality_0  ssn:hasMeasurementCapability  ?WM30_WindDirection_0
      { ?Quality_0  a                   DUL:Quality }
    }
  }
