PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  DUL:  <http://www.loa-cnr.it/ontologies/DUL.owl#>
PREFIX  WM30: <http://purl.oclc.org/NET/ssnx/meteo/WM30#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?WMS301_0
WHERE
  { ?WMS301_0  a                    WM30:WMS301
    { ?WindDirection_0
                ssn:observes  ?WMS301_0
      { ?WindDirection_0
                  a                     WM30:WindDirection
        { ?WindFeature_0
                    DUL:isQualityOf  ?WindDirection_0
          { ?WindFeature_0
                      a                     WM30:WindFeature
          }
        }
      }
    }
  }
