PREFIX  ObjectDescription: <http://ece.neu.edu/ontologies/ObjectDescription3000.owl#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?SensingDevice_0
WHERE
  { ?SensingDevice_0
              a                     ssn:SensingDevice
    { ?Process_0  ssn:implementedBy  ?SensingDevice_0
      { ?Process_0  a                   ssn:Process
        { ?Process_0  ssn:hasOutput  ObjectDescription:Output_instance69 }
      }
    }
  }
