PREFIX  :     <http://ece.neu.edu/ontologies/DeviceDescription3000.owl#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT DISTINCT  ?Sensor_0
WHERE
  { ?Sensor_0  a                    ssn:Sensor
    { ?Process_0  ssn:implements  ?Sensor_0 }
  }
